name: Pull Request

on:
  pull_request:
    branches: [ develop ]
    
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
    
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  job:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery --enable-code-coverage
